#ifndef OBMTSchattenbahnhof_H
#define OBMTSchattenbahnhof_H

const int I2CID_SCHATTENBAHNHOF             = 1;
const int I2CID_SCHATTENBAHNHOF_SENSOREN    = 2;

// I2CID_SCHATTENBAHNHOF
//
const int ID_SCHATTENBAHNHOF_WEICHE_1 = 1;
const int ID_SCHATTENBAHNHOF_WEICHE_2 = 2;
const int ID_SCHATTENBAHNHOF_WEICHE_3 = 3;
const int ID_SCHATTENBAHNHOF_WEICHE_4 = 4;

const int ID_SCHATTENBAHNHOF_GLEIS_1 = 1;
const int ID_SCHATTENBAHNHOF_GLEIS_2 = 2;
const int ID_SCHATTENBAHNHOF_GLEIS_3 = 3;
const int ID_SCHATTENBAHNHOF_GLEIS_4 = 4;
const int ID_SCHATTENBAHNHOF_GLEIS_5 = 5;

// I2CID_SCHATTENBAHNHOF_SENSOREN
//
const int ID_SCHATTENBAHNHOF_GLEIS_1_IR_LINKS       = 1;
const int ID_SCHATTENBAHNHOF_GLEIS_1_IR_RECHTS      = 2;
const int ID_SCHATTENBAHNHOF_GLEIS_2_IR_LINKS       = 3;
const int ID_SCHATTENBAHNHOF_GLEIS_2_IR_RECHTS      = 4;
const int ID_SCHATTENBAHNHOF_GLEIS_3_IR_LINKS       = 5;
const int ID_SCHATTENBAHNHOF_GLEIS_3_IR_RECHTS      = 6;
const int ID_SCHATTENBAHNHOF_GLEIS_4_IR_LINKS       = 7;
const int ID_SCHATTENBAHNHOF_GLEIS_4_IR_RECHTS      = 8;
const int ID_SCHATTENBAHNHOF_GLEIS_5_IR_LINKS       = 9;
const int ID_SCHATTENBAHNHOF_GLEIS_5_IR_RECHTS      = 10;
const int ID_SCHATTENBAHNHOF_EINFAHRT_IR_LINKS      = 11;
const int ID_SCHATTENBAHNHOF_EINFAHRT_IR_RECHTS     = 12;


#endif
