#ifndef OBMTCLIENT1_H
#define OBMTCLIENT1_H

const int CLIENT_SCHATTENBAHNHOF_WEICHE_1 = 1;
const int CLIENT_SCHATTENBAHNHOF_WEICHE_2 = 2;
const int CLIENT_SCHATTENBAHNHOF_WEICHE_3 = 3;
const int CLIENT_SCHATTENBAHNHOF_WEICHE_4 = 4;

#endif
